#version: '3'
services:
  sql-users:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql-users:/docker-entrypoint-initdb.d/

  sql-data:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_SECURE_FILE_PRIV=""
    volumes:
      - ./sql-data:/docker-entrypoint-initdb.d/

  server-website:
    build: ./server-website
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=sql-data
      - MYSQLUSER=root
      - MYSQLPASS=example
      - MYSQLDB=stuff
    volumes:
      - ./server-website/backend:/app/backend
      - ./server-website/frontend:/app/frontend
    ports:
      - "80:80"

  server-users:
    build: ./server-users
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=sql-users
      - MYSQLUSER=root
      - MYSQLPASS=example
      - MYSQLDB=users
      - HASHPEPPER=23af
      - TOTP_SECRET=supersecretcodev2
      - JWTSECRET=jwtsecret
    volumes:
      - ./server-users/backend:/app/backend
    ports:
      - "3000:80"
