#version: '3'
services:
  sql-users:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  sql-data:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  server-data:
    build: ./server-data
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=81
      - MYSQLHOST=sql-data
      - MYSQLUSER=root
      - MYSQLPASS=example
      - JWTSECRET=jwtsecret
    volumes:
      - ./server-data/backend:/app/backend
    ports:
      - "81:81"

  server-users:
    build: ./server-users
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=sql-users
      - MYSQLUSER=root
      - MYSQLPASS=example
    volumes:
      - ./server-users/backend:/app/backend
      - ./server-users/frontend:/app/frontend
    ports:
      - "80:80"
